<?php

namespace DigixBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagDBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagDBRepository extends EntityRepository
{
}
